# Generated by Django 3.2.15 on 2022-10-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='1', max_length=100, null=True)),
                ('client', models.CharField(default='Lord', max_length=100, null=True)),
                ('amount', models.FloatField(default=0.0, null=True)),
                ('order_id', models.CharField(default='ASL20220010', max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
