# Generated by Django 3.2.15 on 2022-11-01 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_subfee_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='1', max_length=100, null=True)),
                ('client', models.CharField(default='Lord', max_length=100, null=True)),
                ('subscribed', models.BooleanField(default=False)),
                ('expires_on', models.DateField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='1', max_length=100, null=True)),
                ('client', models.CharField(default='Lord', max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
