# Generated by Django 3.2.15 on 2022-11-02 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_databasedetails_onetimedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimedetails',
            name='client',
        ),
        migrations.AddField(
            model_name='onetimedetails',
            name='expires_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
