# Generated by Django 3.2.15 on 2023-02-10 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20221102_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasedetails',
            name='expires_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='onetimedetails',
            name='expires_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
