# Generated by Django 3.2.15 on 2022-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='Main', max_length=200, null=True)),
                ('token', models.CharField(default='Main', max_length=200, null=True)),
                ('branch', models.CharField(default='Main', max_length=200, null=True)),
                ('pid', models.IntegerField(default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
