# Generated by Django 3.2.15 on 2023-04-12 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, null=True)),
                ('token', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(default='None', max_length=100, null=True)),
                ('surname', models.CharField(default='None', max_length=100, null=True)),
                ('fullname', models.CharField(default='None', max_length=100, null=True)),
                ('phone', models.CharField(default='None', max_length=100, null=True)),
                ('email', models.CharField(default='None', max_length=100, null=True)),
                ('password', models.CharField(default='None', max_length=100, null=True)),
                ('account_name', models.CharField(default='Demo Account', max_length=200, null=True)),
                ('branch', models.CharField(default='Main', max_length=200, null=True)),
                ('expiry_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('pid', models.CharField(default=0, max_length=200, null=True)),
                ('userId', models.CharField(default=0, max_length=200, null=True)),
                ('unlimited', models.BooleanField(blank=True, default=False, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='email',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='expiry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='firstname',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='fullname',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='password',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='phone',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='session_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='surname',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='unlimited',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='userId',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='account_name',
            field=models.CharField(default='Demo Account', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='pid',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
