# Generated by Django 3.2.15 on 2023-04-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20230412_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetails',
            name='userId',
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='usercode',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
