# Generated by Django 3.2.15 on 2022-10-01 13:45

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, null=True)),
                ('action', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='logo-uploads/')),
                ('assigned_fee', models.IntegerField(default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('account_category', models.CharField(max_length=100)),
                ('membership_size', models.CharField(max_length=20)),
                ('assigned_fee', models.IntegerField(default=0, null=True)),
                ('subscription_duration', models.IntegerField(default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.modules')),
            ],
        ),
        migrations.CreateModel(
            name='AccountSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('json', jsonfield.fields.JSONField(default='', null=True)),
                ('membership_size', models.CharField(max_length=20)),
                ('subscription_duration', models.IntegerField(default=0, null=True)),
                ('renewing_days', models.IntegerField(default=0, null=True)),
                ('remaining_days', models.IntegerField(default=0, null=True)),
                ('expired_days', models.IntegerField(default=0, null=True)),
                ('subscription_fees', models.IntegerField(default=0, null=True)),
                ('paid_by', models.CharField(default='Admin', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.modules')),
            ],
        ),
    ]
