# Generated by Django 3.2.15 on 2022-10-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0003_auto_20221001_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsubscription',
            old_name='subscription_duration',
            new_name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='accountsubscription',
            name='json',
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='description',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='duration',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
