# Generated by Django 3.2.15 on 2022-10-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0004_auto_20221001_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='default',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='ModuleFee',
        ),
    ]
