# Generated by Django 3.2.15 on 2022-10-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0008_auto_20221004_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsubscription',
            old_name='subscription_fees',
            new_name='subscription_fees_ghs',
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='subscription_fees_usd',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
