# Generated by Django 3.2.15 on 2022-10-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0009_auto_20221005_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsubscription',
            old_name='subscription_fees_ghs',
            new_name='subscription_fee_ghs',
        ),
        migrations.RenameField(
            model_name='accountsubscription',
            old_name='subscription_fees_usd',
            new_name='subscription_fee_usd',
        ),
    ]
