# Generated by Django 3.2.15 on 2022-10-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0011_specialmodulefee'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulefee',
            name='amount_to_be_paid_ghs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='modulefee',
            name='amount_to_be_paid_usd',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='specialmodulefee',
            name='amount_to_be_paid_ghs',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='specialmodulefee',
            name='amount_to_be_paid_usd',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
