# Generated by Django 3.2.15 on 2022-10-13 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0012_auto_20221005_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='expires_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
