# Generated by Django 3.2.15 on 2022-10-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0013_accountsubscription_expires_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('subscription_id', models.CharField(max_length=100)),
                ('subscribed_modules', models.JSONField()),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
