# Generated by Django 3.2.15 on 2022-10-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0014_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsubscription',
            name='module',
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='submodules',
            field=models.ManyToManyField(to='superuser.Modules'),
        ),
    ]
