# Generated by Django 3.2.15 on 2022-10-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0015_auto_20221026_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscription',
            name='subscription_fee_ghs',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='accountsubscription',
            name='subscription_fee_usd',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
