# Generated by Django 3.2.15 on 2022-10-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0016_auto_20221026_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='invoice_no',
            field=models.CharField(default='ASL0003', max_length=100, null=True),
        ),
    ]
