# Generated by Django 3.2.15 on 2022-10-26 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0017_accountsubscription_invoice_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialmodulefee',
            name='discount_amount_ghs',
        ),
        migrations.RemoveField(
            model_name='specialmodulefee',
            name='discount_amount_usd',
        ),
        migrations.RemoveField(
            model_name='specialmodulefee',
            name='module',
        ),
        migrations.RemoveField(
            model_name='specialmodulefee',
            name='promo_duration',
        ),
        migrations.RemoveField(
            model_name='specialmodulefee',
            name='promo_membership_size',
        ),
        migrations.RemoveField(
            model_name='specialmodulefee',
            name='respective_increase',
        ),
        migrations.RemoveField(
            model_name='specialmodulefee',
            name='unit_fee_ghs',
        ),
        migrations.RemoveField(
            model_name='specialmodulefee',
            name='unit_fee_usd',
        ),
        migrations.AddField(
            model_name='specialmodulefee',
            name='expires_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='specialmodulefee',
            name='sub_duration',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='specialmodulefee',
            name='submodules',
            field=models.ManyToManyField(to='superuser.Modules'),
        ),
        migrations.AlterField(
            model_name='specialmodulefee',
            name='amount_to_be_paid_ghs',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='specialmodulefee',
            name='amount_to_be_paid_usd',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
