# Generated by Django 3.2.15 on 2022-10-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0018_auto_20221026_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialmodulefee',
            name='expired_days',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='specialmodulefee',
            name='remaining_days',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='specialmodulefee',
            name='renewing_days',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
