# Generated by Django 3.2.15 on 2022-10-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0019_auto_20221026_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialmodulefee',
            name='description',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
