# Generated by Django 3.2.15 on 2022-10-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0020_specialmodulefee_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialmodulefee',
            name='invoice_no',
            field=models.CharField(default='ASP20220003', max_length=100, null=True),
        ),
    ]
