# Generated by Django 3.2.15 on 2022-10-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0021_specialmodulefee_invoice_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('merchant_id', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
