# Generated by Django 3.2.15 on 2022-11-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0023_activationfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='client_id',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='activationfee',
            name='duration',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
