# Generated by Django 3.2.15 on 2022-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0024_auto_20221102_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationfee',
            name='membership_size',
            field=models.CharField(default='0-50', max_length=100, null=True),
        ),
    ]
