# Generated by Django 3.2.15 on 2022-11-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0025_activationfee_membership_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationfee',
            name='membership_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.membershipsizes'),
        ),
    ]
