# Generated by Django 3.2.15 on 2022-11-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0027_auto_20221108_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
