# Generated by Django 3.2.15 on 2022-12-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0028_accountsubscription_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('service_fee', models.FloatField(default=0.0, null=True)),
                ('limit', models.FloatField(default=0.0, null=True)),
                ('outstanding_fee', models.FloatField(default=0.0, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accountsubscription',
            name='client',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
