# Generated by Django 3.2.15 on 2022-12-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0030_clientemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientEmail',
            new_name='EmailDetails',
        ),
    ]
