# Generated by Django 3.2.15 on 2022-12-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0032_tuakausers_verifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuakausers',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile-uploads/'),
        ),
    ]
