# Generated by Django 3.2.15 on 2022-12-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0034_verifications_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitedOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='emaildetails',
            old_name='client',
            new_name='client_name',
        ),
        migrations.AlterField(
            model_name='tuakausers',
            name='image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='profile-uploads/'),
        ),
    ]
