# Generated by Django 3.2.15 on 2023-02-10 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0035_auto_20221222_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscription',
            name='expires_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
