# Generated by Django 3.2.15 on 2023-02-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0036_alter_accountsubscription_expires_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
