# Generated by Django 3.2.15 on 2023-02-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0037_alter_subscriptions_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
