# Generated by Django 3.2.15 on 2023-03-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0041_alter_subscriptions_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
