# Generated by Django 3.2.15 on 2023-04-12 05:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0043_clientsizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='modules',
            field=jsonfield.fields.JSONField(default='', null=True),
        ),
    ]
