# Generated by Django 3.2.15 on 2023-04-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0044_accountsubscription_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('account', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('usercode', models.CharField(max_length=100, null=True)),
                ('profile', models.ImageField(blank=True, default='profile.png', null=True, upload_to='agents-profile-uploads/')),
                ('card', models.ImageField(blank=True, default='profile.png', null=True, upload_to='agents-card-uploads/')),
                ('activation_commission', models.FloatField(default=0.0, null=True)),
                ('renewal_commission', models.FloatField(default=0.0, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
