# Generated by Django 3.2.15 on 2023-04-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0046_auto_20230429_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercode', models.CharField(max_length=100, null=True)),
                ('agent_name', models.CharField(max_length=100, null=True)),
                ('client_id', models.CharField(max_length=100, null=True)),
                ('client_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
