# Generated by Django 3.2.15 on 2023-04-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0047_agentclients'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentclients',
            name='pid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
