# Generated by Django 3.2.15 on 2023-04-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0048_agentclients_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulefee',
            name='agent_unit_fee_ghs',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='modulefee',
            name='agent_unit_fee_usd',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='modulefee',
            name='usercode',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
