# Generated by Django 3.2.15 on 2023-04-30 02:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0049_auto_20230430_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulefee',
            name='agent',
            field=jsonfield.fields.JSONField(default='', null=True),
        ),
    ]
