# Generated by Django 3.2.15 on 2023-04-30 03:22

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0051_auto_20230430_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationfee',
            name='agent_cost',
            field=jsonfield.fields.JSONField(default='', null=True),
        ),
    ]
