# Generated by Django 3.2.15 on 2023-04-30 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0052_activationfee_agent_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsizes',
            name='client_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.membershipsizes'),
        ),
    ]
