# Generated by Django 3.2.15 on 2023-04-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0054_agentclients_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='usercode',
            field=models.CharField(default='ABC12345', max_length=100, null=True),
        ),
    ]
