# Generated by Django 3.2.15 on 2023-04-30 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0055_accountsubscription_usercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscription',
            name='expires_on',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
