# Generated by Django 3.2.15 on 2023-04-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0058_alter_subscriptions_subscribed_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='subscribed_modules',
            field=models.JSONField(default='', null=True),
        ),
    ]
