# Generated by Django 3.2.15 on 2023-05-01 00:42

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0059_alter_subscriptions_subscribed_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscription',
            name='modules',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='activationfee',
            name='agent_cost',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='modulefee',
            name='agent_cost',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='subscribed_modules',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
