# Generated by Django 3.2.15 on 2023-05-02 00:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0060_auto_20230501_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscription',
            name='expires_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
