# Generated by Django 3.2.15 on 2023-05-02 15:28

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0063_subscriptions_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='invoice_copy',
            field=models.CharField(default='ASL0003', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AccountSubscriptionCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='1', max_length=100)),
                ('client', models.CharField(default='None', max_length=100, null=True)),
                ('modules', jsonfield.fields.JSONField(default=dict, null=True)),
                ('membership_size', models.CharField(max_length=20)),
                ('description', models.CharField(default='None', max_length=100)),
                ('duration', models.IntegerField(default=0, null=True)),
                ('amount_paid', models.IntegerField(default=0, null=True)),
                ('renewing_days', models.IntegerField(default=0, null=True)),
                ('remaining_days', models.IntegerField(default=0, null=True)),
                ('expired_days', models.IntegerField(default=0, null=True)),
                ('subscription_fee_usd', models.FloatField(default=0.0, null=True)),
                ('subscription_fee_ghs', models.FloatField(default=0.0, null=True)),
                ('paid_by', models.CharField(default='Admin', max_length=100)),
                ('invoice_no', models.CharField(default='ASL0003', max_length=100, null=True)),
                ('invoice_copy', models.CharField(default='ASL0003', max_length=100, null=True)),
                ('usercode', models.CharField(default='ABC12345', max_length=100, null=True)),
                ('expires_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('confirmed', models.BooleanField(default=False, null=True)),
                ('expired', models.BooleanField(default=False, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('submodules', models.ManyToManyField(to='superuser.Modules')),
            ],
        ),
    ]
