# Generated by Django 3.2.15 on 2023-05-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0067_totalcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='link',
            field=models.CharField(default='https://google.com', max_length=500),
        ),
    ]
