# Generated by Django 3.2.15 on 2023-05-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0068_modules_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='icon',
            field=models.CharField(default='description', max_length=500),
        ),
    ]
