# Generated by Django 3.2.15 on 2023-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0069_modules_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsubscriptioncopy',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
