# Generated by Django 3.2.15 on 2023-05-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0070_auto_20230504_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='non_expiry',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='accountsubscription',
            name='special',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
