# Generated by Django 3.2.15 on 2023-05-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0072_agents_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscriptioncopy',
            name='annual_maintenance_fee',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='agentclients',
            name='gender',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
