# Generated by Django 3.2.15 on 2023-05-06 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0073_auto_20230506_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulefee',
            name='client_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superuser.membershipsizes'),
        ),
    ]
