# Generated by Django 3.2.15 on 2023-05-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0075_accountsubscription_annual_maintenance_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
