# Generated by Django 3.2.15 on 2023-07-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0076_alter_subscriptions_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='merchant_id',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='merchant_account_number',
            field=models.CharField(default='2017254', max_length=100),
        ),
    ]
